/*
 Dynamsoft JavaScript Library
 Product: Dynamsoft Web Twain
 Web Site: http://www.dynamsoft.com

 Copyright 2022, Dynamsoft Corporation 
 Author: Dynamsoft Support Team
 Module: image io js
 Version: 1.7.2
 @20220215173906.008000+480
 Dynamsoft.WasmEnv.busy() && */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.polyfill=function(a,b,c,e){if(b){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in c||(c[d]={});c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof d?a:new d(function(b,d){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){e(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var d=a[b];a[b]=null;try{d()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var d=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(k){b.reject(k)}};d.prototype.createResolveAndReject_=function(){function a(a){return function(f){d||(d=!0,a.call(b,f))}}var b=this,d=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};d.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof d)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};d.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(k){this.reject_(k);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};d.prototype.reject_=function(a){this.settle_(2,a)};d.prototype.fulfill_=function(a){this.settle_(1,a)};d.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)f.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var f=new b;d.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};d.prototype.settleSameAsThenable_=function(a,b){var d=this.createResolveAndReject_();try{a.call(b,d.resolve,d.reject)}catch(l){d.reject(l)}};d.prototype.then=function(a,b){function f(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(u){g(u)}}:b}var c,g,e=new d(function(a,b){c=a;g=b});this.callWhenSettled_(f(a,c),f(b,g));return e};
d.prototype.catch=function(a){return this.then(void 0,a)};d.prototype.callWhenSettled_=function(a,b){function d(){switch(c.state_){case 1:a(c.result_);break;case 2:b(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?f.asyncExecute(d):this.onSettledCallbacks_.push(d)};d.resolve=c;d.reject=function(a){return new d(function(b,d){d(a)})};d.race=function(a){return new d(function(b,d){for(var f=$jscomp.makeIterator(a),e=f.next();!e.done;e=f.next())c(e.value).callWhenSettled_(b,
d)})};d.all=function(a){var b=$jscomp.makeIterator(a),f=b.next();return f.done?c([]):new d(function(a,d){function e(b){return function(d){g[b]=d;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,c(f.value).callWhenSettled_(e(g.length-1),d),f=b.next();while(!f.done)})};return d},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+b++,c)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var e=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(e);if(!e.done)return this.context_.stop_(),e;var d=e.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,d);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(e,d){function f(a){a.done?e(a.value):Promise.resolve(a.value).then(b,c).then(f,d)}f(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,e={next:function(){if(c<a.length){var d=c++;return{value:b(d,a[d]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var d=b.length,f=a.length;c=Math.max(0,Math.min(c|0,b.length));for(var g=0;g<f&&c<d;)if(b[c++]!=a[g++])return!1;return g>=f}},"es6","es3");
$jscomp.polyfill("String.prototype.endsWith",function(a){return a?a:function(a,c){var b=$jscomp.checkStringArgs(this,a,"endsWith");a+="";void 0===c&&(c=b.length);c=Math.max(0,Math.min(c|0,b.length));for(var d=a.length;0<d&&0<c;)if(b[--c]!=a[--d])return!1;return 0>=d}},"es6","es3");var Dynamsoft="undefined"!=typeof Dynamsoft?Dynamsoft:("undefined"!=typeof Dynamsoft?window.Dynamsoft:void 0)||{license:"",workerPathPdfR:"",workerPathPdfW:"",workerPathImgcore:""};Dynamsoft.error=Dynamsoft.error||{};
Dynamsoft.error.code=Dynamsoft.error.code||{};Dynamsoft.error.code.wasmBase=-4E3;Dynamsoft.error.code.wasmException=Dynamsoft.error.code.wasmBase-1;Dynamsoft.error.code.wasmNoModule=Dynamsoft.error.code.wasmBase-1;Dynamsoft.error.code.wasmJsBase=-4100;Dynamsoft.error.code.wasmJsObjectNotInit=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsObjectTerminated=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsObjectInitFailed=Dynamsoft.error.code.wasmJsBase-1;
Dynamsoft.error.code.wasmJsNotLoaded=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsInvalidJson=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsWorkerRunException=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsWorkerRunFailed=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsReadFileFailed=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsCoreTaskException=Dynamsoft.error.code.wasmJsBase-1;
Dynamsoft.error.code.wasmJsProcTaskException=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsSavePdfFailed=Dynamsoft.error.code.wasmJsBase-1;Dynamsoft.error.code.wasmJsSaveTiffFailed=Dynamsoft.error.code.wasmJsBase-1;
Dynamsoft.conststring={version:"1.7.2",logInfo:"logInfo",logDebug:"logDebug",logAll:"logAll",initPending:"pending",initReady:"ready",initFailed:"failed",imgIO:"imgIO",core:"imgCore",imgProc:"imgProc",pdfR:"pdfReader",pdfW:"pdfWriter",crypto:"crypto",binaryBlobType:"application/octet-stream",wasmExtension:".wasm"};Dynamsoft.constDefine={mainIndex:0,pdfReaderIndex:1,wasmDefHeapSize:28};
Dynamsoft.WasmEnv={wasmJSs:["dynamsoft.imageio_wasm-"+Dynamsoft.conststring.version+".js","dynamsoft.pdfReader_wasm-"+Dynamsoft.conststring.version+".js"],wasmHeap:[{maxHeapSize:300,initHeapSize:280},{maxHeapSize:200,initHeapSize:Dynamsoft.constDefine.wasmDefHeapSize}],moduleNames:[Dynamsoft.conststring.imgIO,Dynamsoft.conststring.crypto,Dynamsoft.conststring.core,Dynamsoft.conststring.imgProc,Dynamsoft.conststring.pdfR,Dynamsoft.conststring.pdfW],imgIO:{name:Dynamsoft.conststring.imgIO,autoLoad:!0,
ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.imageio-",wasmModule:null,wasmJSIndex:Dynamsoft.constDefine.mainIndex},imgCore:{name:Dynamsoft.conststring.core,autoLoad:!0,ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.imagecore-",wasmModule:null,wasmJSIndex:Dynamsoft.constDefine.mainIndex},imgProc:{name:Dynamsoft.conststring.imgProc,autoLoad:!0,ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.imageProc-",wasmModule:null,wasmJSIndex:Dynamsoft.constDefine.mainIndex},
pdfReader:{name:Dynamsoft.conststring.pdfR,autoLoad:!1,ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.pdfReader-",wasmModule:null,wasmJSIndex:Dynamsoft.constDefine.pdfReaderIndex},pdfWriter:{name:Dynamsoft.conststring.pdfW,autoLoad:!0,ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.pdfWriter-",wasmModule:null,wasmJSIndex:Dynamsoft.constDefine.mainIndex},crypto:{name:Dynamsoft.conststring.crypto,autoLoad:!0,ver:Dynamsoft.conststring.version,status:"",prefixName:"dynamsoft.crypto-",
wasmModule:null,wasmJSIndex:Dynamsoft.constDefine.mainIndex}};Dynamsoft.WasmEnv.buildWasmFileName=function(a,b,c,e){return a+(e?"sn-":"")+b+c};Dynamsoft.WasmEnv.fetchRetry=function(a,b,c,e){var d=b.retries,f=b.retryDelay;return new Promise(function(g,h){function k(a,b,d){c&&c(e,b);setTimeout(function(){l(++a)},f)}var l=function(f){fetch(a,b).then(function(a){g(a)}).catch(function(a){f<d?k(f,a,null):h(a)})};l(0)})};
Dynamsoft.Enum_ImageType={IT_DIB:-1,IT_RGBA:-2,IT_BGRA:-3,IT_BMP:0,IT_JPG:1,IT_PNG:3,IT_ALL:5};Dynamsoft.Enum_ReturnType={RT_AUTO:-1,RT_BINARY:1,RT_BASE64:2};Dynamsoft.Enum_ErrorMessage={PARAMETER_TYPE_ERROR:"Parameter Type not Supported: ",TIMEOUT:"Timeout no Response: ",FILE_STREAM_ERROR:"File Stream Error: ",WASM_EXCEPTION_ERROR:"An WASM exception occurred."};Dynamsoft.Enum_SimdFlag={SF_DEF:0,SF_ENABLE:1,SF_DISABLE:2};var Dynmasoft=Dynamsoft||{};Dynamsoft.Lib=Dynamsoft.Lib||{};
Dynamsoft.Lib.env=Dynamsoft.Lib.env||{};Dynamsoft.b64ToUint6=function(a){return 64<a&&91>a?a-65:96<a&&123>a?a-71:47<a&&58>a?a+4:43===a?62:47===a?63:0};Dynamsoft.base64DecToArr=function(a,b){a=a.replace(/[^A-Za-z0-9\+\/]/g,"");var c=a.length;b=b?Math.ceil((3*c+1>>>2)/b)*b:3*c+1>>>2;for(var e=new Uint8Array(b),d,f=0,g=0,h=0;h<c;h++)if(d=h&3,f|=Dynamsoft.b64ToUint6(a.charCodeAt(h))<<18-6*d,3===d||1===c-h){for(d=0;3>d&&g<b;d++,g++)e[g]=f>>>(16>>>d&24)&255;f=0}return e};
Dynamsoft.isWasmSupport=function(){try{if("object"===typeof WebAssembly&&"function"===typeof WebAssembly.instantiate){var a=new WebAssembly.Module(Uint8Array.of(0,97,115,109,1,0,0,0));if(a instanceof WebAssembly.Module)return new WebAssembly.Instance(a)instanceof WebAssembly.Instance}}catch(b){}return!1};Dynamsoft.random=function(){return(Date.now()%10086).toString(36).slice(2)+Math.random().toString(36).slice(2)};
Dynamsoft.readFile=function(a){return new Promise(function(b,c){var e=Object.prototype.toString.call(a);if("[object String]"===e)0===a.indexOf("blob:")||0<a.indexOf(".jpg")||0<a.indexOf(".jpeg")||0<a.indexOf(".png")||0<a.indexOf(".bmp")||0<a.indexOf(".dib")||0<a.indexOf(".pdf")||0<a.indexOf(".tiff")||0<a.indexOf(".tif")?fetch(a,{mode:"cors"}).then(function(a){return a.arrayBuffer()}).then(function(a){return b(a)}).catch(function(a){return Promise.reject(a)}):c("Error url: Can not read the file URL");
else if("[object Blob]"===e||"[object FileList]"===e||"[object File]"===e){c=a;if("[object FileList]"===e||"[object File]"===e)c=a[0]?a[0]:a;var d=new FileReader;d.readAsArrayBuffer(c);d.onload=function(){b(d.result)}}else"[object ArrayBuffer]"===e||"[object Uint8ClampedArray]"===e?b(a):c("Not support source type: "+e)})};
Dynamsoft.base64Decode=function(a){function b(a){var b=[],f=a.length,c;for(c=0;c<f;c++){var e=a.charCodeAt(c);if(0==(e>>7&255))b.push(a.charAt(c));else if(6==(e>>5&255)){var k=a.charCodeAt(++c);e=(e&31)<<6;k&=63;e|=k;b.push(String.fromCharCode(e))}else if(14==(e>>4&255)){k=a.charCodeAt(++c);var l=a.charCodeAt(++c);e=e<<4|k>>2&15;k=(k&3)<<6|l&63;e=(e&255)<<8|k;b.push(String.fromCharCode(e))}}return b.join("")}var c=[-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,62,-1,-1,-1,63,52,53,54,55,56,57,58,59,60,61,-1,-1,-1,-1,-1,-1,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,-1,-1,-1,-1,-1,-1,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,-1,-1,-1,-1,-1];return function(a){for(var d=[],f=0,e=a.length,h,k;f<e;){do h=c[a.charCodeAt(f++)&255];while(f<e&&-1==h);if(-1==h)break;do k=c[a.charCodeAt(f++)&255];while(f<e&&-1==k);if(-1==k)break;d.push(String.fromCharCode(h<<
2|(k&48)>>4));do{h=a.charCodeAt(f++)&255;if(61==h)return b(d.join(""));h=c[h]}while(f<e&&-1==h);if(-1==h)break;d.push(String.fromCharCode((k&15)<<4|(h&60)>>2));do{k=a.charCodeAt(f++)&255;if(61==k)return b(d.join(""));k=c[k]}while(f<e&&-1==k);if(-1==k)break;d.push(String.fromCharCode((h&3)<<6|k))}return b(d.join(""))}(a)};Dynamsoft.WasmEnv=Dynamsoft.WasmEnv||{};Dynamsoft.WasmEnv.lastInstanceId=0;Dynamsoft.WasmEnv.worker={maxWorkers:1,liveTime:60};
Dynamsoft.WasmEnv.resourceDir=Dynamsoft.DWT.ResourcesPath+"/src/";Dynamsoft.WasmEnv.logLevel=Dynamsoft.DWT.Debug?Dynamsoft.conststring.logDebug:0;Dynamsoft.WasmEnv.logFunc=null;Dynamsoft.WasmEnv.productKey="";Dynamsoft.WasmEnv.licMode=0;Dynamsoft.WasmEnv.uuid="";Dynamsoft.WasmEnv.fetchOptions={mode:"cors",credentials:"same-origin",retries:3,retryDelay:500};Dynamsoft.WasmEnv.simdFlag=Dynamsoft.Enum_SimdFlag.SF_DEF;Dynamsoft.WasmEnv.useFastcompEdition=!1;
Dynamsoft.WasmEnv.log=function(a,b){var c=Dynamsoft.WasmEnv;c.logLevel===b&&("function"===typeof c.logFunc?c.logFunc(a):console.log(a))};Dynamsoft.WasmEnv.clear=function(a){for(var b=$jscomp.makeIterator(Dynamsoft.WasmEnv.moduleNames),c=b.next();!c.done;c=b.next())if(c=c.value,Dynamsoft.WasmEnv[c].wasmJSIndex==a||void 0==a)Dynamsoft.WasmEnv[c].status="",delete Dynamsoft.WasmEnv[c].error};
Dynamsoft.WasmEnv.setLoglevel=function(a,b){Dynamsoft.WasmEnv.logLevel=1===a?Dynamsoft.conststring.logDebug:0;Dynamsoft.WasmEnv.logFunc=b};
Dynamsoft.WorkerHandler=function(a,b){function c(a){e.terminated=!0;e.options.log("[js]["+Date.now()/1E3+"] worker error "+JSON.stringify(a),e.context);e.terminating&&e.terminationHandler&&e.terminationHandler(e);e.terminating=!1;e.cancelAllTasks()}var e=this;this.options=b||{};this.script=a;this.worker=function(a){if("function"!==typeof Worker&&("object"!==typeof Worker||"function"!==typeof Worker.prototype.constructor))throw Error("Web Workers not supported");a=new Worker(a);a.on=function(a,b){this.addEventListener(a,
function(a){b(a.data)})};a.send=function(a){if(void 0!=a&&void 0!=a.params&&void 0!=a.params.input){var b=Object.prototype.toString.call(a.params.input);if("[object Array]"===Object.prototype.toString.call(a.params.input)){if(b=Object.prototype.toString.call(a.params.input[0]),"[object ArrayBuffer]"===b||"[object Uint8ClampedArray]"===b||"[object Uint8Array]"===b){this.postMessage(a,[void 0!=a.params.input[0].buffer?a.params.input[0].buffer:a.params.input[0]]);return}}else if("[object ArrayBuffer]"===
b||"[object Uint8ClampedArray]"===b||"[object Uint8Array]"===b){this.postMessage(a,[void 0!=a.params.input.buffer?a.params.input.buffer:a.params.input]);return}}this.postMessage(a)};return a}(this.script);this.requestQueue=[];this.terminated=this.terminating=!1;e.tasks=Object.create(null);this.objectToError=function(a){for(var b=Error(""),d=Object.keys(a),c=0;c<d.length;c++)b[d[c]]=a[d[c]];return b};this.dispatchQueuedRequests=function(){e.requestQueue.forEach(e.worker.send.bind(e.worker));e.requestQueue=
[]};this.logDebug=function(a){Dynamsoft.WasmEnv.logLevel===Dynamsoft.conststring.logDebug&&"function"===typeof e.options.log&&e.options.log("[js]["+Date.now()/1E3+"] "+a,e.context)};this.worker.on("message",function(a){"function"===typeof e.options.log&&e.options.log(a.log?a.log:a,e.context);if("string"===typeof a&&"ready"===a)e.worker.ready=!0,e.dispatchQueuedRequests();else if(!a.log){if("object"===typeof a){var b=a.result;"object"===typeof b?(void 0!=b.errorCode&&(b.code=b.errorCode,delete b.errorCode),
void 0!=b.errorMessage&&(b.message=b.errorMessage,delete b.errorMessage)):"string"===typeof b&&(b=b.replace('"errorCode"','"code"'),b=b.replace("'errorCode'","'code'"),b=b.replace('"errorMessage"','"message"'),b=b.replace("'errorMessage'","'message'"),a.result=b);void 0!=a.memSize&&(e.memSize=a.memSize)}b=a.id;var d=e.tasks[b];void 0!==d?(delete e.tasks[b],e.logDebug(a.func+" received"),!0===e.terminating&&e.terminate(),"loadWasm"===a.func&&void 0!=a.result&&(e.worker.wasmReady=!0,e.dispatchQueuedRequests()),
a.error?d.resolver.reject(e.objectToError(a.error)):a.result&&d.resolver.resolve(a.result)):"loadWasm"===a.func&&void 0!=a.result&&Dynamsoft.WasmEnv._handleWasmLoad(a.result,e)}});this.worker.on("error",c);this.worker.on("exit",function(a,b){a="Worker terminated Unexpectedly\n exitCode: `"+(a+"`\n signalCode: `")+(b+"`\n script: `")+(e.script+"`\n");c(Error(a))});this.terminated=this.terminating=!1;this.terminationHandler=null;this.lastTaskId=0};
Dynamsoft.WorkerHandler.prototype.exec=function(a,b,c){c||(c={},c.promise=new Promise(function(a,b){c.resolve=a;c.reject=b}));var e=++this.lastTaskId;this.tasks[e]={id:e,resolver:c};b={id:e,func:a,params:b};Dynamsoft.WasmEnv.logLevel===Dynamsoft.conststring.logDebug&&(b.params.logLevel=Dynamsoft.conststring.logDebug,this.logDebug(a+" send"));this.terminated?c.reject(Error("Worker is terminated")):this.terminating?c.reject(Error("Worker is terminating")):this.worker.wasmReady||this.worker.ready&&"loadWasm"===
a?this.worker.send(b):this.requestQueue.push(b);return c.promise};Dynamsoft.WorkerHandler.prototype.busy=function(){return 0<this.howManyTasks()};Dynamsoft.WorkerHandler.prototype.howManyTasks=function(){return Object.keys(this.tasks).length};Dynamsoft.WorkerHandler.prototype.cancelAllTasks=function(a){for(var b in this.tasks)void 0!==this.tasks[b]&&this.tasks[b].resolver.reject(Error(a));this.tasks=Object.create(null)};
Dynamsoft.WorkerHandler.prototype.alive=function(){return this.terminating||this.terminated?!1:!0};
Dynamsoft.WorkerHandler.prototype.terminate=function(a,b){this.logDebug("worker terminate "+a);a&&this.cancelAllTasks("Worker has been terminated");"function"===typeof b&&(this.terminationHandler=b);if(this.busy())this.terminating=!0;else{if(this.worker){if("function"===typeof this.worker.terminate)this.worker.terminate();else throw Error("Failed to terminate worker");this.worker=null}this.terminating=!1;this.terminated=!0;this.terminationHandler&&this.terminationHandler(this)}};
Dynamsoft.WorkerHandler.prototype.setLogCallback=function(a,b){this.options.log=a;this.context=b};
Dynamsoft.WorkerPool=function(a,b,c,e){var d=this;this.workers=[];this.options=a;this.maxWorkers=1;this.script=this.options.resourceDir+c;this.ready=!1;this.pdfReaderInstance=null;this.terminated=!1;this.wasmLoaderPromise=Object.create(null);this.poolIndex=e;this.crossScript=!1;this._getMaxWorkers=function(){var a=2;"hardwareConcurrency"in self.navigator&&(a=self.navigator.hardwareConcurrency);return Math.max(Math.min(d.options.worker.maxWorkers,Math.max(d.options.worker.maxWorkers,a/2)),1)};this._logAll=
function(a){Dynamsoft.WasmEnv.log(a,Dynamsoft.conststring.logAll)};this._log=function(a,b){Dynamsoft.WasmEnv.log(a,Dynamsoft.conststring.logDebug)};this._createWorker=function(){d.ready&&(d.maxWorkers=d._getMaxWorkers());var a=d.workers;if(a.length<d.maxWorkers){var b=new Dynamsoft.WorkerHandler(d.script);a.push(b);b.id=a.length;b.module={};b.module.modulesInfo=[];b.instances=Object.create(null);b.setLogCallback(this._log,d);d._logAll(a);d.log("get new worker "+b.id+" succeed!");return b}return null};
this._getContainedModuleWorkers=function(a){d._removeTerminatedWorker();var b=d.workers;d._logAll(b);for(var c=[],f=$jscomp.makeIterator(b),e=f.next();!e.done;e=f.next())e=e.value,!e.module.modulesInfo[a.name]||e.busy()&&b.length<d.maxWorkers||c.push(e);d._logAll("get workers for module "+a.name);d._logAll(c);return c};this._checkWorkerValid=function(){d._removeTerminatedWorker();0==d.workers.length&&d.data&&(d.log("no worker ready, reinit"),d.crossScript?d._initAsync(d.data):d._init(d.data))};this._getIdleWorker=
function(){d._removeTerminatedWorker();for(var a=$jscomp.makeIterator(d.workers),b=a.next();!b.done;b=a.next())if(b=b.value,!1===b.busy())return b;return d._createWorker()};this._busy=function(){d._removeTerminatedWorker();for(var a=$jscomp.makeIterator(d.workers),b=a.next();!b.done;b=a.next())if(b.value.busy())return!0;return!1};this._removeTerminatedWorker=function(){d.workers=d.workers.filter(function(a){return!a.terminated})};this._getWorkerByIntanceId=function(a,b){d._logAll("_getWorkerByIntanceId");
d._logAll(a);for(var c=9007199254740991,f=null,e=$jscomp.makeIterator(a),g=e.next();!g.done;g=e.next())if(g=g.value,void 0!=g.instances[b]){f=g;break}else{var m=g.howManyTasks();m<c&&(f=g,c=m)}if(f)return f.instances[b]="",d._logAll(a),d.log("get worker "+b+" in "+f.id+" succeed!"),f;d._logAll("_getWorkerByIntanceId: no suitable worker");return null};this._initWorkerInner=function(a,b,c){try{b.params&&(b.params.resourceDir=this.resourceDir,b.params.fetchOptions=Dynamsoft.WasmEnv.fetchOptions);for(var f=
$jscomp.makeIterator(b.params.module.modulesInfo),e=f.next();!e.done;e=f.next())Dynamsoft.WasmEnv[e.value.name].status=Dynamsoft.conststring.initPending;a.exec(b.func,b.params).then(function(b){void 0===b.code||b.modules?Dynamsoft.WasmEnv._handleWasmLoad(b,a):d.log(b);c()}).catch(function(a){d.log(a);c()})}catch(r){d.log(r),c()}};this._removeInstanceInWorker=function(a,b){var c=d.workers;d._logAll("removeInstanceInWorker");d._logAll(c);for(var f=$jscomp.makeIterator(c),e=f.next();!e.done;e=f.next())if(e=
e.value,e===a){void 0!=e.instances[b]?(delete e.instances[b],d._logAll(c),d.log("removeInstanceInWorker "+b+" in "+e.id+" succeed!")):d.log("not found instance "+b);break}};this._hasInstanceInWorker=function(){for(var a=$jscomp.makeIterator(d.workers),b=a.next();!b.done;b=a.next())if(0!=Object.keys(b.value.instances).length)return!0;return null!=d.pdfReaderInstance};this._getWorker=function(a,b){if(Dynamsoft.WasmEnv[a.name].status==Dynamsoft.conststring.initPending)return this._checkWorkerValid(),
null;var c=d._getContainedModuleWorkers(a);if(0!=c.length)return d._getWorkerByIntanceId(c,b);if(c=d._getIdleWorker()){if(c.module.modulesInfo[a.name])return c;d.log("_getWorker: try to recreate worker "+b);a={id:0,func:"loadWasm",params:{priority:0,key:d.options.productKey,licMode:Dynamsoft.WasmEnv.licMode,uuid:Dynamsoft.WasmEnv.uuid,module:{modulesInfo:[],poolIndex:d.poolIndex,useFastcompEdition:Dynamsoft.WasmEnv.useFastcompEdition}}};b=$jscomp.makeIterator(Dynamsoft.WasmEnv.moduleNames);for(var f=
b.next();!f.done;f=b.next())f=f.value,void 0!=Dynamsoft.WasmEnv[f].poolIndex&&Dynamsoft.WasmEnv[f].poolIndex==d.poolIndex&&a.params.module.modulesInfo.push({name:f,ver:Dynamsoft.WasmEnv[f].ver,wasmModule:Dynamsoft.WasmEnv[f].wasmModule,poolIndex:Dynamsoft.WasmEnv[f].poolIndex,useSimd:Dynamsoft.WasmEnv[f].useSimd});d._initWorkerInner(c,a,function(){})}return null};this._init=function(a){var b=d._createWorker();b&&(b.setLogCallback(function(a,b){b.log(a)},d),a.params.callback=null,d._initWorkerInner(b,
a,function(a){d.maxWorkers=d._getMaxWorkers();d.ready=!0}))};this._initAsync=function(a){var b=this,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){if(1==f.nextAddress)return c=d,f.yield(Dynamsoft.WasmEnv.fetchRetry(d.script,Dynamsoft.WasmEnv.fetchOptions,b._log,b).then(function(a){return a.blob()}).then(function(a){return URL.createObjectURL(a)}),2);c.script=f.yieldResult;d._init(a);f.jumpToEnd()})};this._getPath=function(){this.script.startsWith("http://")||this.script.startsWith("https://")?
this.resourceDir=this.options.resourceDir:this.options.resourceDir.startsWith("/")?null!=location.origin&&(this.resourceDir=location.origin+this.options.resourceDir):null!=location.href&&(this.resourceDir=location.href.substring(0,location.href.lastIndexOf("/")+1)+this.options.resourceDir);this.resourceDir.endsWith("/")||(this.resourceDir+="/");e==Dynamsoft.constDefine.mainIndex&&Dynamsoft.WasmEnv.useFastcompEdition&&(this.resourceDir+="fastcomp/",this.script=this.resourceDir+c)};this._getPath();
b&&0<b.params.module.modulesInfo.length?(!this.script.startsWith("http://")&&!this.script.startsWith("https://")||this.script.startsWith(location.origin)||(this.crossScript=!0),this.data=b,this.crossScript?this._initAsync(b):this._init(b)):(d.maxWorkers=d._getMaxWorkers(),d.ready=!0)};
Dynamsoft.WorkerPool.prototype.getWorker=function(a,b){if(!this.ready)return null;var c=a.name===Dynamsoft.WasmEnv.pdfReader.name;if(c&&this.pdfReaderInstance)return null;if((a=this._getWorker(a,b))&&c){if(this.pdfReaderInstance)return this._removeInstanceInWorker(a,b),null;this.pdfReaderInstance=b}return a};
Dynamsoft.WorkerPool.prototype.removeInstanceInWorker=function(a,b,c,e){this._removeInstanceInWorker(b,c);a.name===Dynamsoft.WasmEnv.pdfReader.name&&this.pdfReaderInstance&&(this.pdfReaderInstance=null);e&&b&&void 0!=b.memSize&&(a=1048576*Dynamsoft.WasmEnv.wasmHeap[this.poolIndex].maxHeapSize,Dynamsoft.WasmEnv.log("current memSize="+b.memSize+", max="+a,Dynamsoft.conststring.logDebug),b.memSize>a&&0!=a&&!this._hasInstanceInWorker()&&(Dynamsoft.WasmEnv.log("reload wasm auto",Dynamsoft.conststring.logDebug),
Dynamsoft.WasmEnv.load(void 0,void 0,void 0,this.poolIndex,!0)))};Dynamsoft.WorkerPool.prototype.log=function(a){Dynamsoft.WasmEnv.log(a,Dynamsoft.conststring.logDebug)};
Dynamsoft.WorkerPool.prototype.terminate=function(a){Dynamsoft.WasmEnv.log("worker pool terminate "+a,Dynamsoft.conststring.logDebug);this.terminated=!0;var b=[],c=this.workers.slice();this.workers=[];c.forEach(function(c){var d={};d.promise=new Promise(function(a,b){d.resolve=a;d.reject=b});b.push(d.promise);c.terminate(a,function(a){d.resolve(a)})});return Promise.all(b)};
Dynamsoft.WorkerPool.prototype.getMemoryUsed=function(){for(var a=[],b=0,c=$jscomp.makeIterator(this.workers),e=c.next();!e.done;e=c.next())(e=e.value)&&void 0!=e.memSize&&(a[b++]=e.memSize);return a};Dynamsoft.WasmEnv.loadPdfReader=function(a,b,c){Dynamsoft.WasmEnv.load(a,b,c,Dynamsoft.constDefine.pdfReaderIndex,!0)};Dynamsoft.WasmEnv.loadMain=function(a,b,c){Dynamsoft.WasmEnv.load(a,b,c,Dynamsoft.constDefine.mainIndex,!0)};
Dynamsoft.WasmEnv.load=function(a,b,c,e,d){Dynamsoft.WasmEnv.unload(e);Dynamsoft.WasmEnv.productKey=void 0!=a?a:Dynamsoft.WasmEnv.productKey;void 0!=b&&(Dynamsoft.WasmEnv.licMode=b?1:0);d=void 0==d?!1:d;Dynamsoft.WasmEnv.uuid=void 0!=c?c:Dynamsoft.WasmEnv.uuid;Dynamsoft.WasmEnv.licenseInfo=void 0;Dynamsoft.WasmEnv.loadingPromise={};Dynamsoft.WasmEnv.loadingPromise.promise=new Promise(function(a,b){Dynamsoft.WasmEnv.loadingPromise.resolve=a;Dynamsoft.WasmEnv.loadingPromise.reject=b});var f=Dynamsoft.WasmEnv;
f.clear(e);void 0===Dynamsoft.WorkerPool.Instances&&(Dynamsoft.WorkerPool.Instances=[]);void 0!=e?Dynamsoft.WorkerPool.Instances[e]=null:Dynamsoft.WorkerPool.Instances=[];for(b=0;b<f.wasmJSs.length;b++)if(void 0==e||e==b)c={id:0,func:"loadWasm",params:{priority:0,key:a,licMode:Dynamsoft.WasmEnv.licMode,uuid:Dynamsoft.WasmEnv.uuid,module:{modulesInfo:[],poolIndex:b,useFastcompEdition:Dynamsoft.WasmEnv.useFastcompEdition},callback:function(a){f.logLevel===Dynamsoft.conststring.logDebug&&("function"===
typeof f.logFunc?f.logFunc(a):console.log(a))}}},(d||f.imgCore.autoLoad)&&f.imgCore.wasmJSIndex==b&&(c.params.module.modulesInfo.push({name:f.imgIO.name,ver:f.imgIO.ver,wasmModule:f.imgIO.wasmModule,poolIndex:b}),f.imgIO.poolIndex=b,1===Dynamsoft.WasmEnv.licMode&&(c.params.module.modulesInfo.push({name:f.crypto.name,ver:f.crypto.ver,wasmModule:f.crypto.wasmModule,poolIndex:b}),f.crypto.poolIndex=b)),(d||f.imgCore.autoLoad||f.imgCore.wasmModule)&&f.imgCore.wasmJSIndex==b&&(c.params.module.modulesInfo.push({name:f.imgCore.name,
ver:f.imgCore.ver,wasmModule:f.imgCore.wasmModule,poolIndex:b}),f.imgCore.poolIndex=b),(d||f.imgProc.autoLoad||f.imgProc.wasmModule)&&f.imgProc.wasmJSIndex==b&&(f.imgProc.useSimd=Dynamsoft.WasmEnv.getUseSimd(),c.params.module.modulesInfo.push({name:f.imgProc.name,ver:f.imgProc.ver,wasmModule:f.imgProc.wasmModule,poolIndex:b,useSimd:f.imgProc.useSimd}),f.imgProc.poolIndex=b),(d||f.pdfReader.autoLoad||f.pdfReader.wasmModule)&&f.pdfReader.wasmJSIndex==b&&(c.params.module.modulesInfo.push({name:f.pdfReader.name,
ver:f.pdfReader.ver,wasmModule:f.pdfReader.wasmModule,poolIndex:b}),f.pdfReader.poolIndex=b),(d||f.pdfWriter.autoLoad||f.pdfWriter.wasmModule)&&f.pdfWriter.wasmJSIndex==b&&(c.params.module.modulesInfo.push({name:f.pdfWriter.name,ver:f.pdfWriter.ver,wasmModule:f.pdfWriter.wasmModule,poolIndex:b}),f.pdfWriter.poolIndex=b),Dynamsoft.WorkerPool.Instances[b]=0!=c.params.module.modulesInfo.length?new Dynamsoft.WorkerPool(f,c,f.wasmJSs[b],b,Dynamsoft.WasmEnv.maxHeapSize,Dynamsoft.WasmEnv.initH):null};
Dynamsoft.WasmEnv.unloadMain=function(){return Dynamsoft.WasmEnv.unload(Dynamsoft.constDefine.mainIndex)};Dynamsoft.WasmEnv.unloadPdfReader=function(){return Dynamsoft.WasmEnv.unload(Dynamsoft.constDefine.pdfReaderIndex)};
Dynamsoft.WasmEnv.getUseSimd=function(){if(Dynamsoft.WasmEnv.useFastcompEdition)return!1;if(Dynamsoft.WasmEnv.simdFlag===Dynamsoft.Enum_SimdFlag.SF_DEF){if(void 0!=navigator.userAgentData&&void 0!=navigator.userAgentData.brands)for(var a=$jscomp.makeIterator(navigator.userAgentData.brands),b=a.next();!b.done;b=a.next())if(b=b.value,b.brand&&("Chromium"==b.brand||"Google Chrome"==b.brand)&&b.version&&94<=parseInt(b.version,10))return!0}else if(Dynamsoft.WasmEnv.simdFlag===Dynamsoft.Enum_SimdFlag.SF_ENABLE)return!0;
return!1};Dynamsoft.WasmEnv.unload=function(a){var b=Dynamsoft.WorkerPool.Instances;if(void 0!=b){if(void 0!=a)return b[a]?b[a].terminate(!0):!0;a=[];b=$jscomp.makeIterator(b);for(var c=b.next();!c.done;c=b.next())a.push(c.value.terminate(!0));return a}return Promise.resolve()};Dynamsoft.WasmEnv.getWorkerPool=function(a){var b=Dynamsoft.WorkerPool.Instances;return b?(a=b[a],!a||a.terminated?null:a):null};
Dynamsoft.WasmEnv.busy=function(a){var b=Dynamsoft.WorkerPool.Instances;if(b){if(void 0!=a)return b[a]?b[a].busy():!1;a=$jscomp.makeIterator(b);for(b=a.next();!b.done;b=a.next())if(b.value._busy())return!0}return!1};
Dynamsoft.WasmEnv._handleWasmLoad=function(a,b){Dynamsoft.WasmEnv.log("handleWasmLoad:",Dynamsoft.conststring.logDebug);Dynamsoft.WasmEnv.log(a,Dynamsoft.conststring.logDebug);if("object"!=typeof a||void 0==a.modules)"object"===typeof a&&Dynamsoft.WasmEnv.loadingPromise.reject({code:a.code,message:a.message});else{for(var c=$jscomp.makeIterator(a.modules),e=c.next();!e.done;e=c.next())e=e.value,a.code?(Dynamsoft.WasmEnv[e.name].error={code:a.code,message:a.message},b.module.modulesInfo[e.name]=!1):
(delete Dynamsoft.WasmEnv[e.name].error,Dynamsoft.WasmEnv[e.name].status=Dynamsoft.conststring.initReady,Dynamsoft.WasmEnv[e.name].wasmModule=e.wasmModule,b.module.modulesInfo[e.name]=!0);a.licenseInfo&&(a=a.licenseInfo,"string"===typeof a&&(a=JSON.parse(a),Dynamsoft.WasmEnv.licenseInfo=a),Dynamsoft.WasmEnv.loadingPromise.resolve(a));void 0!=Dynamsoft.WasmEnv.imgIO.error&&Dynamsoft.WasmEnv.loadingPromise.reject(Dynamsoft.WasmEnv.imgIO.error)}};
Dynamsoft.ImageIoBase=function(a,b,c,e){var d=this;this.moduleInfo=b;this.name=this.moduleInfo.name;this.outputType=Dynamsoft.Enum_ImageType.IT_JPG;this.inputType=Dynamsoft.Enum_ImageType.IT_ALL;this.tiffFormat=0;this.jpegQuality=80;this.tasksQueue=[];this.worker=null;this.lastTaskId=0;this.logFunc=c;this.context=e;this.instanceId=++Dynamsoft.WasmEnv.lastInstanceId;this.timer=null;this.nv=JSON.parse(JSON.stringify(Dynamsoft.navInfo));this.mb=Dynamsoft.Lib.env.bMobile;this.dm=location.origin;this.initStatus=
"";this.terminated=!1;this.license=a?a:Dynamsoft.license;this.license||(this.license="");this.licMode=Dynamsoft.WasmEnv.licMode;this.uuid=Dynamsoft.WasmEnv.uuid;this._getWorker=function(){d.timer&&clearTimeout(d.timer);if(d.worker&&d.worker.alive())return d.worker;var a=Dynamsoft.WasmEnv.getWorkerPool(d.moduleInfo.poolIndex);if(a){d.worker=a.getWorker(d.moduleInfo,d.instanceId);if(d.worker&&d.worker.alive())0<d.tasksQueue.length&&d._dispatchQueuedTasks();else{if(Dynamsoft.WasmEnv[d.name].error)return d._cancelAllTasks(Dynamsoft.error.code.wasmJsNotLoaded,
Dynamsoft.WasmEnv[d.name].error),d.worker;0<d.tasksQueue.length&&(d.timer=setTimeout(d._getWorker,50))}return d.worker}d._cancelAllTasks(Dynamsoft.error.code.wasmJsNotLoaded,"wasm env not loaded")};this._dispatchQueuedTasks=function(){d._logAll(d.tasksQueue,d);if(d.worker&&d.worker.alive()){if(0<d.tasksQueue.length){var a=d.tasksQueue[0];if(d.initStatus===Dynamsoft.conststring.initReady||"init"===a.func)delete d.tasksQueue[0],d.tasksQueue.splice(0,1),d._exec(a)}}else d.worker&&!d.worker.alive()&&
0<d.tasksQueue.length&&"init"!=d.tasksQueue[0].func?(d.worker=null,d._init()):0<d.tasksQueue.length&&d._getWorker()};this._log=function(a,b){"function"===typeof b.logFunc?b.logFunc(a,b.context):Dynamsoft.WasmEnv.log(a,Dynamsoft.conststring.logDebug)};this._logAll=function(a,b){Dynamsoft.WasmEnv.logLevel===Dynamsoft.conststring.logAll&&this._log(a,b)};this._handleReject=function(a,b,d){var c=b;"object"!=typeof c&&(c={},c.code=d,c.message=b);return this.terminated?a.resolve(c):a.reject(c)};this._handleBasicResult=
function(a,b){delete a.code;delete a.message;return a};this._handleBooleanResult=function(a,b){return!0};this._createImageResult=function(a,b,d){return d?void 0!=b?new Blob([a],{type:b}):new Blob([a]):a};this._handleImageData=function(a,b){if("object"===typeof a.imageData)if(void 0!=a.imageCount&&1<a.imageCount)for(var d=0;d<a.imageCount;d++)a.imageData[d]=b.context._createImageResult(a.imageData[d],a.blobType,b.params.returnBlob);else a.imageData=b.context._createImageResult(a.imageData,a.blobType,
b.params.returnBlob);"object"===typeof a.pdfData&&(a.pdfData=b.context._createImageResult(a.pdfData,a.blobType,b.params.returnBlob));return a};this._handleResult=function(a,b){a=b.context._getResult(a);void 0===a.code||!a.code&&"Successful."===a.message?(a=b.handleResult(a,b),d._dispatchQueuedTasks(),b=b.resolve,b(a)):(a={code:a.code,message:a.code===Dynamsoft.error.code.wasmException?Dynamsoft.Enum_ErrorMessage.WASM_EXCEPTION_ERROR:a.message},this.terminated?b.resolve(a):b.reject(a))};this._getResult=
function(a){try{return"string"===typeof a?JSON.parse(a):a}catch(g){return a}};this._exec=function(a){var b=d.worker;b.setLogCallback(d._log,d);d._logAll(a,d);try{b.exec(a.func,a.params).then(function(b){d._log(b,d);d._handleResult(d._getResult(b),a)}).catch(function(b){d._log(b,d);d._dispatchQueuedTasks();var c=b;"object"===typeof b&&void 0!=b.message&&(c=b.message);b={code:Dynamsoft.error.code.wasmJsWorkerRunFailed,message:c};d.terminated?a.resolve(b):a.reject(b)})}catch(h){d._dispatchQueuedTasks(),
d._log(h,d),b={code:Dynamsoft.error.code.wasmJsWorkerRunException,message:h.message,stack:h.stack},d.terminated?a.resolve(b):a.reject(b)}};this._cancelAllTasks=function(a,b){for(var c=$jscomp.makeIterator(d.tasksQueue),e=c.next();!e.done;e=c.next())if(e=e.value,void 0!==e){var f={code:a,message:b};d.terminated?e.resolve(f):e.reject(f)}d.tasksQueue=[]};this._createTask=function(a,b,d){var c={id:++this.lastTaskId};c.promise=new Promise(function(a,b){c.resolve=a;c.reject=b});c.func=a;c.params={moduleName:this.name,
insId:this.instanceId,fetchOptions:Dynamsoft.WasmEnv.fetchOptions,initHeapSize:Dynamsoft.WasmEnv.wasmHeap[this.moduleInfo.poolIndex].initHeapSize};c.context=this;c.handleResult="undefined"!==typeof d&&d?d:this._handleBasicResult;c.params.input="undefined"!==typeof b&&b?b:"";c.params.returnType="";c.params.returnBlob=!0;return c};this._addTask=function(a,b){""===this.initStatus?a.reject({code:Dynamsoft.error.code.wasmJsObjectNotInit,message:this.terminated?"object has been disposed":"object not init"}):
this.initStatus===Dynamsoft.conststring.initFailed?a.reject({code:Dynamsoft.error.code.wasmJsObjectInitFailed,message:d.initError}):(b?d.tasksQueue.unshift(a):d.tasksQueue.push(a),d._dispatchQueuedTasks());return a.promise};this._init=function(){var a=this._createTask("init");a.params.key=this.license;a.params.uuid=this.uuid;a.params.licMode=this.licMode;a.params.val={nv:this.nv,mb:this.mb,dm:this.dm};a.handleResult=function(a,b){b.context.initStatus=Dynamsoft.conststring.initReady;return a};this.initStatus=
Dynamsoft.conststring.initPending;this._addTask(a,!0);a.promise.then(function(a){d._log(d.name+" init return: ",d);d._log(a,d)}).catch(function(a){d.initStatus=Dynamsoft.conststring.initFailed;d.initError=a.message;d._log(d.name+" init failed",d);d._log(a,d);d._cancelAllTasks(Dynamsoft.error.code.wasmJsObjectInitFailed,a.message)})};this._destroy=function(){var a=this._createTask("destroy");this._addTask(a);return a.promise};this._terminate=function(a){var b=this._destroy();this.terminated=!0;var c=
Dynamsoft.WasmEnv.getWorkerPool(d.moduleInfo.poolIndex);c&&c.removeInstanceInWorker(d.moduleInfo,d.worker,d.instanceId,a);b.then(function(a){d.worker=null;d._log(d.name+" destroy return: ",d);d._log(a,d)}).catch(function(a){d.worker=null;d._log(d.name+" destroy failed",d);d._log(a,d)});this.initStatus=""};this._readFile=function(a,b){return new Promise(function(c,e){Dynamsoft.readFile(a).then(function(a){c(a)},function(a){d._handleReject(b,a,Dynamsoft.error.code.wasmJsReadFileFailed)}).catch(function(a){d._handleReject(b,
a,Dynamsoft.error.code.wasmJsReadFileFailed)})})};this._init()};Dynamsoft.ImageIoBase.prototype.terminate=function(a){this._terminate(void 0!=a?a:!0)};
Dynamsoft.ImageIoBase.prototype.downloadData=function(a,b,c,e){a=a?a:Date.now()+"";return(new Promise(function(d,f){if(b){if("base64"===c){var g=Dynamsoft.base64DecToArr(b).buffer;g=new Blob([g],{type:"pdf"==e?"application/pdf":"jpg"==e?"image/jpeg":"image/"+e});g=URL.createObjectURL(g)}else"blob"===c?g=b:f(Dynamsoft.Enum_ErrorMessage.FILE_STREAM_ERROR+"Please read/write image or get page before download!");a=a+"."+e;window.navigator.msSaveBlob&&fetch(g).then(function(a){return a.arrayBuffer()}).then(function(b){b=
new Blob([b]);window.navigator.msSaveOrOpenBlob(b,a);d(a)});f=document.createElement("a");f.href=g;f.download=a;f.click();d(a)}else f(Dynamsoft.Enum_ErrorMessage.FILE_STREAM_ERROR+"Please read/write image or get page before download!")})).catch(function(a){return Promise.reject(a)})};
Dynamsoft.Imagecore=function(a,b,c){a=a?a:Dynamsoft.WasmEnv.productKey;Dynamsoft.ImageIoBase.call(this,a,Dynamsoft.WasmEnv.imgCore,b,c);this.saveImageInner=function(a,b,c,g,h,k,l,r,m,t){var d=this;b=void 0!=b?b:this.inputType;c=void 0!=c?c:0;g=void 0!=g?g:0;h=void 0!=h?h:24;k=void 0!=k?k:96;l=void 0!=l?l:96;r=void 0!=r?r:this.outputType;m=void 0!=m?m:this.jpegQuality;t=void 0!=t?t:Dynamsoft.Enum_ReturnType.RT_AUTO;var e=d._createTask("SaveImage");d._readFile(a,e).then(function(a){e.params.input=[a,
b,c,g,h,k,l,r,m];e.params.returnType=t;e.params.returnBlob=t!=Dynamsoft.Enum_ReturnType.RT_BASE64;e.handleResult=d._handleImageData;d._addTask(e)});return e.promise}};Dynamsoft.Imagecore.prototype=Object.create(Dynamsoft.ImageIoBase.prototype);Dynamsoft.Imagecore.prototype.constructor=Dynamsoft.Imagecore;Dynamsoft.Imagecore.prototype.getImageFormat=function(a){var b=this,c=b._createTask("GetImageFormat");b._readFile(a,c).then(function(a){c.params.input=a;b._addTask(c)});return c.promise};
Dynamsoft.Imagecore.prototype.readImageInfo=function(a){var b=this,c=b._createTask("ReadImageInfo");b._readFile(a,c).then(function(a){c.params.input=a;b._addTask(c)});return c.promise};Dynamsoft.Imagecore.prototype.getMD5=function(a){var b=this,c=b._createTask("GetMD5");b._readFile(a,c).then(function(a){c.params.input=a;c.handleResult=function(a,b){return a.MD5};b._addTask(c)});return c.promise};Dynamsoft.Imagecore.prototype.getLicenseInfo=function(){return this._addTask(this._createTask("GetLicenseInfo"))};
Dynamsoft.Imagecore.prototype.getAesResult=function(a){return this._addTask(this._createTask("GetAesResult",[void 0!=a?a:""]))};Dynamsoft.Imagecore.prototype.saveImage=function(a,b,c,e){return this.saveImageInner(a,null,null,null,null,null,null,b,c,e)};
Dynamsoft.Imagecore.prototype.readImage=function(a,b,c,e){b=void 0!=b?b:this.outputType;c=void 0!=c?c:this.jpegQuality;e=void 0!=e?e:!1;var d=this,f=d._createTask("ReadImage");d._readFile(a,f).then(function(a){f.params.input=[a,b,c];f.params.returnType=e?Dynamsoft.Enum_ReturnType.RT_BASE64:Dynamsoft.Enum_ReturnType.RT_AUTO;f.params.returnBlob=!e;f.handleResult=d._handleImageData;d._addTask(f)});return f.promise};
Dynamsoft.Imagecore.prototype.openTiff=function(a){var b=this,c=b._createTask("LoadTiff");b._readFile(a,c).then(function(a){c.params.input=a;b._addTask(c)});return c.promise};
Dynamsoft.Imagecore.prototype.readTiff=function(a,b,c){a=void 0!=a?a:0;b=void 0!=b?b:this.outputType;c=void 0!=c?c:this.returnImageAsBase64;var e=this._createTask("ReadTiffPage");e.params.input=[a,b];e.params.returnType=c?Dynamsoft.Enum_ReturnType.RT_BASE64:Dynamsoft.Enum_ReturnType.RT_AUTO;e.params.returnBlob=!c;e.handleResult=this._handleImageData;return this._addTask(e)};Dynamsoft.Imagecore.prototype.closeTiff=function(){return this._addTask(this._createTask("EndReadTiff",null,this._handleBooleanResult))};
Dynamsoft.Imagecore.prototype.createTiff=function(){return this._addTask(this._createTask("NewTiff",null,this._handleBooleanResult))};Dynamsoft.Imagecore.prototype.appendImage=function(a,b,c,e){b=void 0!=b?b:this.inputType;c=void 0!=c?c:this.tiffFormat;e=void 0!=e?e:this.jpegQuality;var d=this,f=d._createTask("AppendImageToTiff");d._readFile(a,f).then(function(a){f.params.input=[a,b,c,e];f.handleResult=d._handleBooleanResult;d._addTask(f)});return f.promise};
Dynamsoft.Imagecore.prototype.addTag=function(a,b,c){return this._addTask(this._createTask("AddTagToNextPage",[a,b,void 0!=c?c:!1],this._handleBooleanResult))};Dynamsoft.Imagecore.prototype.getTiff=function(a){var b=this._createTask("GetTiffStream");b.handleResult=this._handleImageData;b.params.returnType=void 0!=a?a:Dynamsoft.Enum_ReturnType.RT_AUTO;b.params.returnBlob=a!=Dynamsoft.Enum_ReturnType.RT_AUTO;return this._addTask(b)};
Dynamsoft.Imagecore.prototype.getMemoryUsed=function(){return this._addTask(this._createTask("getMemoryUsed",null,function(a,b){return a.memoryUsed}))};Dynamsoft.Imagecore.prototype.getMultiPartFile=function(a,b){return this._addTask(this._createTask("ds_get_file",[a,b],function(a,b){return a}))};Dynamsoft.ImageProc=function(a,b,c){a=a?a:Dynamsoft.WasmEnv.productKey;Dynamsoft.ImageIoBase.call(this,a,Dynamsoft.WasmEnv.imgProc,b,c)};Dynamsoft.ImageProc.prototype=Object.create(Dynamsoft.ImageIoBase.prototype);
Dynamsoft.ImageProc.prototype.constructor=Dynamsoft.ImageProc;
Dynamsoft.ImageProc.prototype.initImage=function(a,b,c,e,d){b=void 0!=b?b:!1;c=void 0!=c?c:0;e=void 0!=e?e:0;d=void 0!=d?d:!1;var f=this,g=f._createTask("InitImageObject");g.params.input=[a,c,e];b||d?(b?g.params.input.push(Dynamsoft.Enum_ImageType.IT_RGBA):g.params.input.push(Dynamsoft.Enum_ImageType.IT_BGRA),f._addTask(g)):f._readFile(a,g).then(function(a){g.params.input[0]=a;g.params.input.push(Dynamsoft.Enum_ImageType.IT_ALL);f._addTask(g)});return g.promise};
Dynamsoft.ImageProc.prototype.rotate=function(a,b,c,e){a=void 0!=a?a:0;if(0>a||360<a)a%=360,0>a&&(a+=360);return this._addTask(this._createTask("RotateEx",[a,void 0!=c?c:!1,void 0!=e?e:3,void 0!=b?b:"FFFFFF"],this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.flip=function(a){a=void 0!=a?a:1;var b=this._createTask("");b.handleResult=this._handleBooleanResult;1===a?b.func="Flip":-1===a&&(b.func="Mirror");this._addTask(b);return b.promise};
Dynamsoft.ImageProc.prototype.erase=function(a,b,c,e,d){d=void 0!=d?d:"FFFFFF";var f=this._createTask("Erase");f.handleResult=this._handleBooleanResult;f.params.input=[a,b,c,e,d];this._addTask(f);return f.promise};Dynamsoft.ImageProc.prototype.crop=function(a,b,c,e){return this._addTask(this._createTask("Crop",[a,b,c,e],this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.resize=function(a,b,c){return this._addTask(this._createTask("ChangeImageSize",[a,b,void 0!=c?c:5],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.toGrayscale=function(a){a=void 0!=a?a:1;1>a&&(a=1);3<a&&(a=3);var b="";1===a?b="0":2===a?b="3;3;720;1.05":3===a&&(b="3;5;1080;1.05");return this._addTask(this._createTask("ConvertToGrayScale",b,this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.toBinary=function(a,b){b=void 0!=b?b:1;1>b&&(b=1);3<b&&(b=3);var c="";void 0!=a&&(a?c="1":1===b?c="0":2===b?c="2;3;720;1.05":3===b&&(c="2;5;1080;1.05"));return this._addTask(this._createTask("ConvertToBWScale",c,this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.invert=function(){return this._addTask(this._createTask("Invert",null,this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.setImageWidth=function(a,b){return this._addTask(this._createTask("SetImageWidth",[a,void 0!=b?b:"FFFFFF"],this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.setImageHeight=function(a,b){return this._addTask(this._createTask("SetImageHeight",[a,void 0!=b?b:"FFFFFF"],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.setDPI=function(a,b,c,e,d,f){return this._addTask(this._createTask("SetDPI",[a,b,c,e,void 0!=d?d:!1,f],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.getImage=function(a,b,c,e,d,f,g,h){a=void 0!=a?a:this.jpegQuality;b=void 0!=b?b:!0;e=void 0!=e?e:0;d=void 0!=d?d:0;f=void 0!=f?f:0;g=void 0!=g?g:!0;h=void 0!=c&&c&&void 0==h?Dynamsoft.Enum_ImageType.IT_JPG:void 0!=h?h:Dynamsoft.Enum_ImageType.IT_ALL;c=this._createTask("GetCurrentImage");c.params.input=[h,e,d,f,!1,a,b];c.params.returnBlob=g;c.handleResult=this._handleImageData;return this._addTask(c)};
Dynamsoft.ImageProc.prototype.getSkewAngle=function(a){return this._addTask(this._createTask("GetSkewAngle",[void 0!=a?a:""],function(a,c){return a.skewAngle}))};Dynamsoft.ImageProc.prototype.freeReservedData=function(){return this._addTask(this._createTask("FreeReservedData",null,this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.detectDocument=function(a,b,c,e,d){return this._addTask(this._createTask("DocumentDetect",[void 0!=a?a:2,(void 0!=b?b:75)/100,void 0!=c?c:100,(void 0!=e?e:0)/255,void 0!=d?d:""]))};Dynamsoft.ImageProc.prototype.perspective=function(a,b,c,e,d,f,g,h){return this._addTask(this._createTask("Perspective",[a,b,c,e,d,f,g,h],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.changeBrightness=function(a,b){a=void 0!=a?a:0;b=void 0!=b?b:1;0!=b&&1!=b&&(b=0);return 1===b?this._addTask(this._createTask("ChangeBrightnessAndContrast",[a,0],this._handleBooleanResult)):this._addTask(this._createTask("ChangeBrightness",[Math.floor(a/1E3*255)],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.changeContrast=function(a,b){a=void 0!=a?a:0;b=void 0!=b?b:1;0!=b&&1!=b&&(b=0);return 1===b?this._addTask(this._createTask("ChangeBrightnessAndContrast",[0,a],this._handleBooleanResult)):this._addTask(this._createTask("ChangeContrast",[1+a/1E3],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.removeShadow=function(a,b){a=void 0!=a?a:1;b=void 0!=b?b:1.05;1>a&&(a=1);3<a&&(a=3);var c="5";1===a?c+=";3;720;"+b:2===a?c+=";5;1080;"+b:3===a&&(c+=";10;0;"+b);return this._addTask(this._createTask("ShadowRemovel",[c],this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.enhanceAndSharpenImage=function(){return this._addTask(this._createTask("EnhanceAndSharpen",[""],this._handleBooleanResult))};
Dynamsoft.ImageProc.prototype.brighten=function(){return this._addTask(this._createTask("Brighten",[""],this._handleBooleanResult))};Dynamsoft.ImageProc.prototype.getBlurryScore=function(){return this._addTask(this._createTask("GetBlurScore",[""],function(a,b){return a.blurryScore}))};
Dynamsoft.ImageProc.prototype.drawQuadrangle=function(a,b,c,e,d,f,g,h,k,l){strParameter=(void 0!=k?k:"FFFFFF")+";"+(void 0!=l?l:5);return this._addTask(this._createTask("DrawQuadrangle",[a,b,c,e,d,f,g,h,strParameter],this._handleBooleanResult))};Dynamsoft.ImageProcWrapper={};
Dynamsoft.ImageProcWrapper.resize=function(a,b,c,e,d){if(0>=e||e>=b&&e>=c)return{imageData:a};var f=new Dynamsoft.ImageProc(Dynamsoft.WasmEnv.productKey);return f.initImage(a).then(function(){var a=void 0==d?5:d;var h=b>c?b/e:c/e;return f.resize(Math.floor(b/h+.5),Math.floor(c/h+.5),a)}).then(function(){return f.getImage()}).then(function(a){f.terminate();return a},function(a){f.terminate();return a})};
function rotatePoints(a,b,c,e){for(var d=[],f=0;f<a.length;f+=2){var g=a[f];var h=a[f+1];if(90==b)var k=c-h;else 180==b?(k=c-g,g=e-h):270==b?(k=h,g=e-g):(k=g,g=h);d.push(k,g)}return d}
Dynamsoft.ImageProcWrapper.createImage=function(a){var b,c,e,d,f,g,h,k,l,r,m,t,B,C,u,D,v,w,x,p,z,A,q,E,y;return $jscomp.asyncExecutePromiseGeneratorProgram(function(n){switch(n.nextAddress){case 1:b=new Dynamsoft.ImageProc(Dynamsoft.WasmEnv.productKey);n.setFinallyBlock(2);c={src:null,result:null,preview:null};e=a.source;d=a.output;f=e.imageWidth||e.width;g=e.imageHeight||e.height;h=e.imageData||e.data;if(void 0==d||void 0==d.orgImage&&void 0==d.previewImage)return n.return(c);k=void 0!=e.rgba?e.rgba:
!1;l=void 0!=e.bgra?e.bgra:!1;r=void 0!=a.doPerspective?a.doPerspective:!1;m=e.angle||0;return n.yield(b.initImage(h,k,f,g,l),4);case 4:t=n.yieldResult;c.src=t.srcBuffer;if(!r||!a.polygon){n.jumpTo(5);break}return n.yield(b.perspective(a.polygon.points[0],a.polygon.points[1],a.polygon.points[2],a.polygon.points[3],a.polygon.points[4],a.polygon.points[5],a.polygon.points[6],a.polygon.points[7]),5);case 5:if(0==m){n.jumpTo(7);break}if(0>m||360<m)m%=360,0>m&&(m+=360);return n.yield(b.rotate(m),7);case 7:if(!d.orgImage){n.jumpTo(9);
break}B=void 0==d.orgImage.returnBlob?!0:d.orgImage.returnBlob;C=void 0!=e.imageBitDepth?e.imageBitDepth:void 0;u=void 0!=e.imageXResolution?e.imageXResolution:void 0;D=void 0!=e.imageYResolution?e.imageYResolution:void 0;return n.yield(b.getImage(d.orgImage.quality,!1,k|l,C,u,D,B,d.orgImage.returnType),10);case 10:v=n.yieldResult,d.orgImage.returnType==Dynamsoft.Enum_ImageType.IT_BGRA?v.bgra=!0:d.orgImage.returnType==Dynamsoft.Enum_ImageType.IT_RGBA&&(v.rgba=!0),c.result=v;case 9:if(!d.previewImage){n.jumpTo(11);
break}w=f;x=g;if(90==m||270==m)w=g,x=f;p=Math.min(d.previewImage.width/w,d.previewImage.height/x);90==m||270==m?(z=Math.floor(g*p+.5),A=Math.floor(f*p+.5)):(z=Math.floor(f*p+.5),A=Math.floor(g*p+.5));return n.yield(b.resize(z,A,d.previewImage.nInterplationMethod),12);case 12:if(!a.polygon||r){n.jumpTo(13);break}q=a.polygon.points;0!=m&&(q=rotatePoints(q,m,w,x));return n.yield(b.drawQuadrangle(Math.floor(q[0]*p+.5),Math.floor(q[1]*p+.5),Math.floor(q[2]*p+.5),Math.floor(q[3]*p+.5),Math.floor(q[4]*p+
.5),Math.floor(q[5]*p+.5),Math.floor(q[6]*p+.5),Math.floor(q[7]*p+.5),a.polygon.strokeColor,a.polygon.lineWidth),13);case 13:return E=void 0==d.previewImage.returnBlob?!0:d.previewImage.returnBlob,n.yield(b.getImage(d.previewImage.quality,!0,k|l,void 0,void 0,void 0,E,d.previewImage.returnType),15);case 15:y=n.yieldResult,d.previewImage.returnType==Dynamsoft.Enum_ImageType.IT_BGRA?y.bgra=!0:d.previewImage.returnType==Dynamsoft.Enum_ImageType.IT_RGBA&&(y.rgba=!0),c.preview=y;case 11:return n.return(c);
case 2:n.enterFinallyBlock(),b.terminate(),n.leaveFinallyBlock(0)}})};Dynamsoft.PdfReader=function(a,b,c){a=a?a:Dynamsoft.WasmEnv.productKey;Dynamsoft.ImageIoBase.call(this,a,Dynamsoft.WasmEnv.pdfReader,b,c);this.resolution=200;this.readMode=3;this.outputType=Dynamsoft.Enum_ImageType.IT_ALL};Dynamsoft.PdfReader.prototype=Object.create(Dynamsoft.ImageIoBase.prototype);Dynamsoft.PdfReader.prototype.constructor=Dynamsoft.PdfReader;
Dynamsoft.PdfReader.prototype.open=function(a,b){b=void 0!=b?b:"";var c=this,e=c._createTask("LoadPdf");c._readFile(a,e).then(function(a){e.params.input=[a,b];e.handleResult=function(a,b){var d=Dynamsoft.base64Decode(a.infoBase64);try{try{d.replace(/\\/gi,"\\\\");var c=JSON.parse(d)}catch(l){c=d}return{PdfCount:a.pageCount,PdfInfo:c,isTextBased:a.isTextBased}}catch(l){b.reject({code:Dynamsoft.error.code.wasmJsInvalidJson,message:l.message,stack:l.stack})}};c._addTask(e)});return e.promise};
Dynamsoft.PdfReader.prototype.readPage=function(a,b,c,e,d,f){a=void 0!=a?a:0;b=void 0!=b?b:this.resolution;c=void 0!=c?c:this.readMode;e=void 0!=e?e:this.outputType;f=void 0!=f?f:this.returnImageAsBase64;d=void 0!=d?d:!1;var g=this._createTask("ReadPdfPage");g.params.input=[a,b,c,e,d];g.params.returnType=f?Dynamsoft.Enum_ReturnType.RT_BASE64:Dynamsoft.Enum_ReturnType.RT_AUTO;g.params.returnBlob=!f;g.handleResult=this._handleImageData;return this._addTask(g)};
Dynamsoft.PdfReader.prototype.close=function(){return this._addTask(this._createTask("UnloadPdf",null,this._handleBooleanResult))};Dynamsoft.PdfWriter=function(a,b,c){a=a?a:Dynamsoft.WasmEnv.productKey;Dynamsoft.ImageIoBase.call(this,a,Dynamsoft.WasmEnv.pdfWriter,b,c);this._setPdfSettings=function(a){var b={};if(void 0!=a&&"object"===typeof a)for(var c in a)b[c]=a[c];return b}};Dynamsoft.PdfWriter.prototype=Object.create(Dynamsoft.ImageIoBase.prototype);Dynamsoft.PdfWriter.prototype.constructor=Dynamsoft.PdfWriter;
Dynamsoft.PdfWriter.prototype.initPdfSetting=function(a){var b=this._createTask("InitPdfWriter");b.params.input=JSON.stringify(this._setPdfSettings(a));b.handleResult=this._handleBooleanResult;return this._addTask(b)};Dynamsoft.PdfWriter.prototype.appendPage=function(a){var b=this,c=b._createTask("AddPageFromImageFileStream");b._readFile(a,c).then(function(a){c.params.input=a;c.handleResult=b._handleBooleanResult;b._addTask(c)});return c.promise};
Dynamsoft.PdfWriter.prototype.writePdf=function(a){var b=this._createTask("GetPdfContent");b.params.returnType=void 0!=a?a:Dynamsoft.Enum_ReturnType.RT_AUTO;b.params.returnBlob=a!=Dynamsoft.Enum_ReturnType.RT_AUTO;b.handleResult=this._handleImageData;return this._addTask(b)};Dynamsoft.pdf=Dynamsoft.pdf||{};
Dynamsoft.pdf.IsModuleInstalled=function(){return Dynamsoft.isWasmSupport()?Dynamsoft.WasmEnv.pdfReader.status==Dynamsoft.conststring.initReady&&Dynamsoft.WasmEnv.pdfWriter.status==Dynamsoft.conststring.initReady:!1};
Dynamsoft.WasmEnv.getLicenseInfo=function(a,b,c){Dynamsoft.WasmEnv.productKey==a&&Dynamsoft.WasmEnv.licenseInfo?a=Promise.resolve(Dynamsoft.WasmEnv.licenseInfo):(Dynamsoft.WasmEnv.productKey=a,Dynamsoft.WasmEnv.licMode=void 0!=b?b?1:0:0,Dynamsoft.WasmEnv.uuid=void 0!=c?c:"",a=new Promise(function(a,b){var c=new Dynamsoft.Imagecore(Dynamsoft.WasmEnv.productKey);c.getLicenseInfo().then(function(b){c.terminate();Dynamsoft.WasmEnv.licenseInfo=b;a(b)},function(a){c.terminate();b(a)})}));return a};
Dynamsoft.WasmEnv.getWorkerPoolSize=function(){var a=Dynamsoft.WorkerPool.Instances;return a?a.length:0};Dynamsoft.WasmEnv.getMemoryUsed=function(){var a=Dynamsoft.WorkerPool.Instances;if(a){var b=[];a=$jscomp.makeIterator(a);for(var c=a.next();!c.done;c=a.next())c=c.value,null===c||c.terminated?b.push(0):b.push(c.getMemoryUsed());return b}return[]};
Dynamsoft.WasmEnv.getWasmNames=function(){for(var a=[],b=$jscomp.makeIterator(Dynamsoft.WasmEnv.moduleNames),c=b.next();!c.done;c=b.next())c=c.value,a.push(Dynamsoft.WasmEnv.buildWasmFileName(Dynamsoft.WasmEnv[c].prefixName,Dynamsoft.WasmEnv[c].ver,Dynamsoft.conststring.wasmExtension,!1));return a};
